[build]
  publish = "dist/public"
  command = "./build.sh"

[build.environment]
  NODE_VERSION = "18"
  CACHE_BUST = "v8-filesystem-fix"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-v2/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"